### ISSUE TITLE
Icon request - Lollypop

### ISSUE THREAD

**Issue by anaturinbor** [snwh/moka-icon-theme#208]
Lollypop is a new GNOME music playing application. https://github.com/gnumdk/lollypop

Original icon:
![icon](https://cloud.githubusercontent.com/assets/10692755/12077158/6082215e-b1dc-11e5-9bb0-7ce243eb085c.png)

[Desktop Entry]
Name=Lollypop
Icon=lollypop
Exec=lollypop %U
Terminal=false
Type=Application
Categories=GNOME;GTK;AudioVideo;Player;Audio;

**Comment by gnumdk** [comment]
The icon name is now org.gnome.Lollypop ;)

--
Lollypop dev
