### ISSUE TITLE
Icon Request - Teamviewer

### ISSUE THREAD

**Issue by Aeirex** [snwh/moka-icon-theme#212]
There needs to be a fixed icon for Teamviewer, it is pretty popular piece of software. It also is blurry and ugly in Alt + Tab.

**Comment by snwh** [comment]
There is an icon for teamviewer, in Moka

**Comment by ebkalderon** [comment]
@snwh Unfortunately, this icon does not seem to work at all with TeamViewer 11. I am using Moka straight from Git and can confirm this behavior.

**Comment by snwh** [comment]
Teamviewer has a hardcoded icon. I can't fix this directly.

**Comment by ebkalderon** [comment]
Makes sense. That's a shame.

**Comment by johnbeard** [comment]
@ebkalderon Check out [hardcode-fixer](https://github.com/Foggalong/hardcode-fixer) for a work-around (basically it replaces the hardcoded icon with a symlink to a theme icon).

**Comment by gjallarhorn** [comment]
This is actually just a stupid desktop file configuration from Teamviewer.
To fix it, just edit `/usr/share/applications/teamviewer-teamviewer11.desktop` and change the following line: `Icon=/opt/teamviewer/tv_bin/desktop/teamviewer.png` to `Icon=teamviewer`
:smiley:
