### ISSUE TITLE
Polari and GNOME Maps icons broken

### ISSUE THREAD

**Issue by ebkalderon** [snwh/moka-icon-theme#238]
For some reason, the launchers for these applications still have the default GNOME icons. I am using the latest revision of Moka, compiled straight from Git, with GNOME 3.20.

**Comment by ElvisPresly** [comment]
Confirm

**Comment by ebkalderon** [comment]
Seems to be fixed by commit cf2f493dde185ef897a943d463a5996fbaa9a409. If anyone else can confirm, this issue can be closed.

**Comment by ElvisPresly** [comment]
You can close the ticket, icons look good
