### ISSUE TITLE
Ubuntu 16.04 - Software not changing icon

### ISSUE THREAD

**Issue by Svendheim** [snwh/moka-icon-theme#251]
Hello!

I Used Git to install the latest version. 
Then I chose Moka with Unity Tweak, and as you can see from the uploaded picture, the Ubuntu Software icon does not change. Everything else seems to be fine.

![ubuntusoftware](https://cloud.githubusercontent.com/assets/20624479/17083728/277fd87a-51a9-11e6-8113-b87ad6edccbb.png)

**Comment by Svendheim** [comment]
If I edit **/usr/share/ubuntu/applications/org.gnome.Software.desktop**, it seems to work.
Is it not a bit weird that this .desktop file is in its own folder, and not **/usr/share/applications**?

Is it possible for you guys to fix this straight from the package? :)

Cheers!

**Comment by dyskette** [comment]
What was the value of `Icon=` in *org.gnome.Software.desktop*.

**Comment by Svendheim** [comment]
Icon=ubuntusoftware
