### ISSUE TITLE
Icon Request: Scribus

### ISSUE THREAD

**Issue by rmordico** [snwh/moka-icon-theme#336]
### Icon Request

- Scribus / Scribus NG / Scribus Daily
- Professional layout and publishing software supporting EPS and SVG import/export, and PDF support. 
- `https://www.scribus.net/
![scribus_header-91](https://cloud.githubusercontent.com/assets/26463096/24003277/572b98fc-0a63-11e7-8cde-abec38b9af32.png)

**Comment by corsinbaumgartner** [comment]
There is already an icon for Scribus.
Source: my computer.

**Comment by NikoKrause** [comment]
https://github.com/snwh/moka-icon-theme/blob/master/Moka/96x96/apps/scribus.png

**Comment by snwh** [comment]
Yep already in there
