### ISSUE TITLE
Terminix rebranded as Tilix

### ISSUE THREAD

**Issue by ebkalderon** [snwh/moka-icon-theme#338]
The Terminix project has just been renamed to `Tilix`, so the Moka icon for it no longer works. The desktop file has been renamed from `com.gexperts.Terminix.desktop` to `com.gexperts.Tilix.desktop`. Symlinking the two should resolve the problem.

**Comment by hlavij** [comment]
ebkalderon, how exactly to symling it? Thanks

**Comment by ebkalderon** [comment]
@hlavij For each instance of `com.gexperts.Terminix.png` found in this repository, create a symbolic link in the exact same folder called `com.gexperts.Tilix.png`. Pretty simple fix.

**Comment by snwh** [comment]
I have a script for linking things quickly, I'll have this done in a future commit.

**Comment by ebkalderon** [comment]
Since this issue has been fixed by #359, I think this issue should be closed.
