### ISSUE TITLE
Icon repackaging/resizing

### ISSUE THREAD

**Issue by fravaccaro** [snwh/moka-icon-theme#344]
Good evening, 

As I wanted to package Moka for Sailfish OS, I generated the icons from the svg files but, as a result, I had an icon on the left and a row of icons on the right in the generated png. 

I'm not an image manipulator expert, this is the code I used to resize them:

inkscape -f $file -w 86 -h 86 -e $destfolder

Is there anything I miss? I'd not want to start resizing from the already available PNGs.

Br,

Fra

**Comment by snwh** [comment]
Well the icons are not SVG so you can't resize them with Inkscape. And none of the icons are 86x86 so resizing them will crunch the icons and they'd look bad.

Your best bet is to use `convert`

```bash
convert $f -size 86x86 $f.resized.png
```
