### ISSUE TITLE
Icon Request: Zotero

### ISSUE THREAD

**Issue by 73** [snwh/moka-icon-theme#355]
### Icon Request

- **application name:** Zotero 
- **short description** Zotero [zoh-TAIR-oh] is a free, easy-to-use tool to help you collect, organize, cite, and share your research sources.
- `icon-file-name` *what am I supposed to write here?*

**Please attach an image of or the original icon file for reference.**
![default48](https://cloud.githubusercontent.com/assets/529346/26404285/a2294b2e-4091-11e7-9044-4f6079b4dd21.png)

**Comment by voanhcuoc** [comment]
> icon-file-name what am I supposed to write here?

The name that desktop file will look up, e.g. Icon field in `/usr/share/applications/zotero.desktop`

**Comment by pixelou** [comment]
Zotero icon is correctly found on archlinux using the following .desktop file:
https://aur.archlinux.org/cgit/aur.git/tree/zotero.desktop?h=zotero

**Comment by snwh** [comment]
Zotero is already in the theme
