### ISSUE TITLE
Is Moka icons still updated?

### ISSUE THREAD

**Issue by chuutatsu** [snwh/moka-icon-theme#362]
I am using the latest available Moka icons and it appears that it is missing a lot of icons. 

Is Moka icons still updated? Or going to be abandoned in the future>

**Comment by snwh** [comment]
It gets updates periodically and missing icons do get added, people just have to tell me what they are

**Comment by snwh** [comment]
But yes, development is not as active as it used to be since I've moved onto other things (this theme is over 5 years old).

**Comment by chuutatsu** [comment]
Glad that Moka is still continued albeit slow. Since this is already answered, I'll close this. 

Thank you.
