### ISSUE TITLE
Deja dup icon

### ISSUE THREAD

**Issue by pauloue** [snwh/moka-icon-theme#368]
On fedora 26 I installed deja-dup with `sudo dnf install deja-dup`. The icon file name in the .desktop file is org.gnome.DejaDup, which is not the same as the Moka icon title for it. So I'm seeing the default icon instead of the Moka icon. After editing the desktop file to use `deja-dup` as the icon it works.

**Comment by pauloue** [comment]
This seems to be related to #356 based on the name of the icon file, but I installed it with dnf, not flatpack.

**Comment by snwh** [comment]
fixed
