### ISSUE TITLE
Mokka Icons cause Linux Mint 18.3 to open folders only with triple click

### ISSUE THREAD

**Issue by bosselmann** [snwh/moka-icon-theme#374]
On Linux Mint 18.3 the Mokka Icons cause the folders only to be opened with a triple click. I think its the same with LM 18.1 and 18.2 too. 

See some details on similar problems with icon causing triple clicks here:
https://forums.linuxmint.com/viewtopic.php?t=239339

**Comment by fossfreedom** [comment]
sounds more like a bug in caja  than for here.

**Comment by bosselmann** [comment]
hmm maybe you are right. I ve tested now different icon sets, all have the same problem.

**Comment by snwh** [comment]
Yeah would have nothing to do with the icons
