### ISSUE TITLE
(Icon Request) elementaryOS Screenshot Utiluity

### ISSUE THREAD

**Issue by Schyken** [snwh/moka-icon-theme#386]
### Icon Request

If you are making an icon request please edit this template accordingly. If you have another issue, delete all this and carry on.

- screenshot-tool
- elementaryOS screenshot utility
- `accessories-screenshot`

![accessories-screenshot](https://user-images.githubusercontent.com/20944747/36950885-de0e2166-1fb9-11e8-843d-06ffce8667c7.png)

**Comment by snwh** [comment]
fixed

**Comment by Schyken** [comment]
Ah wow, thanks!
