### ISSUE TITLE
Icon Request: Abrowser

### ISSUE THREAD

**Issue by baconicsynergy** [snwh/moka-icon-theme#388]
### Icon Request

- application name: Abrowser
- short description: Fork of Firefox found in Trisquel GNU/Linux
- `icon-file-name`: abrowser.desktop

![abrowser_icon](https://user-images.githubusercontent.com/13252153/39502528-46a4f1ae-4db0-11e8-9546-ee05a8e29a99.png)

**Comment by snwh** [comment]
added
