### ISSUE TITLE
Fix broken GNOME application icons

### ISSUE THREAD

**Issue by ebkalderon** [snwh/moka-icon-theme#390]
There are several GNOME applications whose icons are no longer responding to the Moka icon theme. The issue is that the `Icon` names they request in the latest versions of their `.desktop` files do not exist anywhere in Moka. The solution to this would be to add some symlinks to existing icons.

Please see the table below of application names, the `Icon` names they request, and the existing Moka icons they need to be symlinked to:

Application | Expected Icon  | Moka Equivalent Icon
---|---|---
DConf Editor | `ca.desrt.dconf-editor` | `dconf-editor`
Geary | `org.gnome.Geary` | `email`
GNOME Boxes | `org.gnome.Boxes` | `gnome-boxes`
GNOME Contacts | `org.gnome.Contacts` | `addressbook`
GNOME Tweaks | `org.gnome.tweaks` | `gnome-tweak-tool`

**Comment by snwh** [comment]
@ebkalderon I see your dotfiles fix to .desktop files isn't necessary, it'd be easier to create symlinks in the moka icons ;)

**Comment by snwh** [comment]
And these are all included in Moka currently as symlinks

**Comment by ebkalderon** [comment]
@snwh I am keenly aware of that. Hence the request for new symlinks in my original post, so I may remove those workarounds. Thank you for addressing the issue nonetheless!
