### ISSUE TITLE
PPA: Moka icons won't build on Artful and newer

### ISSUE THREAD

**Issue by wfwf1997** [snwh/moka-icon-theme#391]
The package from PPA suffers from building failure on Artful and newer version of Ubuntu. According to the build log, `meson` is missing for building them. Is it possible to add `meson` to build dependencies to make auto build work again?

**Comment by snwh** [comment]
It doesn’t need meson to build the packages and the packaging instructions don’t require them. I don’t know why the build server is trying that.

**Comment by wfwf1997** [comment]
The project has changed from `autotools` to `meson` as build system, so `meson` becomes a build dependency. In the newer version of `debhelper`, it can detect `meson` as build system and then auto configure it. However, `debhelper` provided in `Xenial` is an older version which lacks support in `meson`. That is why packages in old version of Ubuntu seems to be built successfully. But the `.deb` generated takes only several KiBs, which means it is not properly packaged as well.  
I think either add `meson` to build dependencies or manually override `dh_install` target can solve the problem.

**Comment by wfwf1997** [comment]
Make `rules` in `debian` folder like this and everything got solved:
```makefile
#!/usr/bin/make -f

#export DH_VERBOSE = 1
%:
        dh $@

override_dh_auto_configure:

override_dh_missing:
        dh_missing --fail-missing
```
This makes `dh_auto_configure` do nothing. And original `dh_install` can just put every icon just in place.

**Comment by snwh** [comment]
Ahhhh, that's the bit I don't have in the rules. https://git.launchpad.net/~moka/moka-icon-theme/+git/packaging/tree/debian/rules

**Comment by wfwf1997** [comment]
Remember to remove the whole `override_dh_install` section or it will do nothing when installing.

**Comment by snwh** [comment]
I have an `install` file though

**Comment by wfwf1997** [comment]
Problem is that you also overrode `dh_install` behavior using `override_dh_install`, but `install` file is actually handled by the original `dh_install`. So you need to remove remove this section or it would put nothing to the package.

**Comment by snwh** [comment]
I wasn't having problems with the install process however

**Comment by wfwf1997** [comment]
It _is_ built successfully. But just have a look at the `buildlog`, it contains no icons at all:
```
moka-icon-theme_5.4.518-201806241606~daily~ubuntu18.10.1_all.deb
----------------------------------------------------------------

 new debian package, version 2.0.
 size 2076 bytes: control archive=828 bytes.
     399 bytes,    12 lines      control              
     158 bytes,     2 lines      md5sums              
     298 bytes,    19 lines   *  postinst             #!/bin/sh
      44 bytes,     0 lines   *  prerm                
 Package: moka-icon-theme
 Version: 5.4.518-201806241606~daily~ubuntu18.10.1
 Architecture: all
 Maintainer: Sam Hewitt <sam@snwh.org>
 Installed-Size: 11
 Depends: faba-icon-theme
 Section: gnome
 Priority: optional
 Homepage: https://github.com/snwh/moka-icon-theme
 Description: Moka Icon Theme
  Moka is a stylized Tango-esque Linux desktop icon set.
  They are designed to be clear, simple and consistent.

drwxr-xr-x root/root         0 2018-06-24 16:11 ./
drwxr-xr-x root/root         0 2018-06-24 16:11 ./usr/
drwxr-xr-x root/root         0 2018-06-24 16:11 ./usr/share/
drwxr-xr-x root/root         0 2018-06-24 16:11 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-06-24 16:11 ./usr/share/doc/moka-icon-theme/
-rw-r--r-- root/root       311 2018-06-24 16:11 ./usr/share/doc/moka-icon-theme/changelog.Debian.gz
-rw-r--r-- root/root       682 2018-06-24 16:11 ./usr/share/doc/moka-icon-theme/copyright
drwxr-xr-x root/root         0 2018-06-24 16:11 ./usr/share/icons/
```

**Comment by snwh** [comment]
Does anyone enjoy debian packaging??

**Comment by wfwf1997** [comment]
Actually I was an Arch Linuxer and also enjoy using Fedora. The packaging system of Debian is the most complex among the three. In Arch Linux you just need a `PKGBUILD` and in Fedora/RHEL you need a `.spec`, but in Debian, too many things to deal with. Ahhh, so annoying.

**Comment by snwh** [comment]
@wfwf1997 I know, I used to do both of those as well for this project and related projects and they were so much easier to deal with.

**Comment by snwh** [comment]
Alright! that buildlog looks right now, thanks for your help I was having the same problem across all my icon sets.

**Comment by snwh** [comment]
Things seem to be working. Heck that would have been a simple fix had I found it, online documentation on debian packaging is horrible.
