### ISSUE TITLE
Icon Request: ksystemlog

### ISSUE THREAD

**Issue by snwh** [snwh/moka-icon-theme#393]
### Icon Request
from email: `ksystemlog`

**Comment by CottonEaster** [comment]
As I've said in an e-mail, it's actually the _Faba_ theme that lacks the icon. The Moka theme has the icon. My mistake. Sorry. I'd be happy enough were the Moka icon just copied to the Faba theme, I think.

**Comment by snwh** [comment]
Ah, well the Faba theme isn't meant to contain extra app icons. It's just a very minimal sub-theme for the Moka set.

**Comment by CottonEaster** [comment]
Hmm. When I tell Linux Mint to use the Faba icons, my dock (Plank) looks like this:

![faba](https://user-images.githubusercontent.com/9998846/42536856-214073e0-848b-11e8-9128-088e13106d25.png)

By contrast, here's the dock using Moka:

![moka](https://user-images.githubusercontent.com/9998846/42536859-249857f6-848b-11e8-84de-ccd2e0e2baf0.png)

Ah, but do you mean the following? The Faba icons provide alternatives for some of the Moka icons; but most icons in the two sets are identical?

At any rate: I like the way my icons - on the dock and elsewhere - look using the Faba set; but, using that Faba set, I do lack an icon for ksystemlog (see the blank-ish icon towards the middle of the dock in the first picture).

**Comment by snwh** [comment]
What I mean is that Faba is just a set of generic icons. It doesn't provide icons for any apps, except the generic ones like `utilities-terminal`. I wouldn't include a `ksystemlog` in Faba just like I wouldn't include a Firefox icon, that's what Moka is for.

The consistency between how the icons look is only because the two themes are related. 

:thinking: You would only see that blank-ish icon when the app itself doesn't have an icon, which is odd.

**Comment by CottonEaster** [comment]
Ah, so, when the theme does not provide an icon, the _application itself_ should do so? Right. But this is not working for the Faba icons. When I have the Faba icon theme selected, both plank and desktop launchers show a generic icon for ksystemlog - whereas, when I use another icon theme, ksystemlog gets a non-generic icon.

Reinstalling ksystemguard made no difference.

Is this a Mint (or Cinnamon) problem, a Ksysguard problem, or a Faba problem? (The flipside of the joy of Linux is the problem assigning responsibility.)

**Comment by CottonEaster** [comment]
Let me add: I would switch to the Paper theme and be done with it - for I prefer that to Faba, anyway - but, as I think I reported to you via a separate e-mail, simply installing the Paper icon theme - and not fiddling with the mouse theme - results in gigantic carets in some applications.

**Comment by snwh** [comment]
Using Faba as a standalone icon set isn't really ideal for a lot of folks, it's a lot like using just the GNOME/Adwaita icon set (which also wouldn't have a ksystemlog icon). Themes like Paper, Moka and others ship 1000s of icons for "third-party" apps.

You can use the Paper icon set and not the Paper cursor set, unless Mint does some silly thing and sets them both at the same time.

**Comment by CottonEaster** [comment]
Thanks. _Yet_,

1. the point that I thought I'd managed to grasp was as follows. _Even if Faba lacks an icon for X, my dock and desktop should still be able to display a non-generic icon for X_. Other icon themes manage this. _Why doesn't Faba_, for this particular icon?

2. _As to paper_, I've filed _a separate bug report_ - [here](https://github.com/snwh/paper-icon-theme/issues/678) (paper, issue #678).

**Comment by snwh** [comment]
I understand what's you're saying. My point is that, bluntly, I'm not going put a `ksystemlog` icon in Faba since that's out of the scope of the project.

Why ksystemlog is not display an icon would be an issue with that app or with its .desktop file (you can check as see what it specifies for it `Icon=` field)
